# Generated by Django 5.2 on 2026-04-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='host',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='groupchat',
        ),
        migrations.RemoveField(
            model_name='groupchatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='user',
        ),
        migrations.RemoveField(
            model_name='page',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pagepost',
            name='user',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='GroupChatMessage',
        ),
        migrations.DeleteModel(
            name='GroupPost',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PagePost',
        ),
    ]
