# Generated by Django 5.2 on 2026-05-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_images_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='whatsApp',
        ),
    ]
